AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CrowdTracker - Project

Parameters:
  Mode:
    Type: String
    Description: Build mode
    Default: development
    AllowedValues:
      - development
      - stage
      - production

Resources:
  Core:
    Type: AWS::Serverless::Application
    Properties:
      Location: core/template.yaml
      Parameters:
        Mode: !Ref Mode
      Tags:
        application: crowd-tracker
        module: project
        environment: !Ref Mode

  Backend:
    Type: AWS::Serverless::Application
    DependsOn: Core
    Properties:
      Location: backend/template.yaml
      Parameters:
        Mode: !Ref Mode
        TableName: !GetAtt Core.Outputs.TableName
      Tags:
        application: crowd-tracker
        module: project
        environment: !Ref Mode

Outputs:
  ApiUrl:
    Value: !GetAtt Backend.Outputs.ApiUrl
    Description: GraphQL api url
