AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CrowdTracker - Project

Parameters:
  Mode:
    Type: String
    Description: Build mode
    Default: development
    AllowedValues:
      - development
      - stage
      - production

Resources:
  Core:
    Type: AWS::Serverless::Application
    Properties:
      Location: core/template.yaml
      Parameters:
        Mode: !Ref Mode
      Tags:
        application: crowd-tracker
        module: project
        environment: !Ref Mode

  Backend:
    Type: AWS::Serverless::Application
    DependsOn: Core
    Properties:
      Location: backend/template.yaml
      Parameters:
        Mode: !Ref Mode
        TableName: !GetAtt Core.Outputs.TableName
        UserPoolId: !GetAtt Core.Outputs.UserPoolId
      Tags:
        application: crowd-tracker
        module: project
        environment: !Ref Mode

Outputs:
  Region:
    Value: !Ref AWS::Region
    Description: Project deployment's region
  UserPoolId:
    Value: !GetAtt Core.Outputs.UserPoolId
    Description: Cognito user pool id
  UserPoolWebClientId:
    Value: !GetAtt Core.Outputs.UserPoolWebClientId
    Description: Cognito user pool web client id
  UserPoolDomain:
    Value: !GetAtt Core.Outputs.UserPoolDomain
    Description: Url for federated user pool domain
  AppSyncUrl:
    Value: !GetAtt Backend.Outputs.AppSyncUrl
    Description: URL for appsync api
  ApiAuthenticationType:
    Value: !GetAtt Backend.Outputs.ApiAuthenticationType
    Description: Main appsync API authentication type
