AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CrowdTracker - Core

Parameters:
  Mode:
    Type: String
    Description: Build mode
    Default: development
    AllowedValues:
      - development
      - stage
      - production

Mappings:
  ModeMap:
    development:
      ModeSuffix: -dev
    stage:
      ModeSuffix: -test
    production:
      ModeSuffix: ''

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub
        - 'crowd-tracker${suffix}'
        - suffix: !FindInMap [ModeMap, !Ref Mode, ModeSuffix]
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      AttributeDefinitions:
        - 
          AttributeName: pk
          AttributeType: S
        - 
          AttributeName: sk
          AttributeType: S
        - 
          AttributeName: gsi1pk
          AttributeType: S
      KeySchema:
        - 
          AttributeName: pk
          KeyType: HASH
        - 
          AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - 
          IndexName: gsi1
          KeySchema:
            - 
              AttributeName: gsi1pk
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2
      Tags:
        - Key: application
          Value: crowd-tracker
        - Key: module
          Value: core
        - Key: environment
          Value: !Ref Mode

Outputs:
  TableName:
    Value: !Ref DynamoDBTable
    Description: DynamoDB table name
